//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankSummaries
    {
        public int id { get; set; }
        public Nullable<byte> bankId { get; set; }
        public Nullable<short> YSpences { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string MonthName { get; set; }
        public Nullable<byte> MonthNumber { get; set; }
    }
}
