//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMap
    {
        public int id { get; set; }
        public string Cod { get; set; }
        public string Category { get; set; }
        public Nullable<byte> Nivel { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> CreatedInApp { get; set; }
        public Nullable<bool> ImagenAnadidaEnApp { get; set; }
        public Nullable<bool> VisibleInApps { get; set; }
    }
}
