//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividendos
    {
        public int id { get; set; }
        public byte CompanyID { get; set; }
        public short Year { get; set; }
        public Nullable<decimal> DividendosEfectivo { get; set; }
        public Nullable<decimal> DividendosAccion { get; set; }
        public Nullable<int> AccionesPrecedentes { get; set; }
        public Nullable<decimal> AccionesPorAccion { get; set; }
        public Nullable<decimal> EfectivoPorAccion { get; set; }
        public string Distribute { get; set; }
        public string Graph { get; set; }
        public Nullable<decimal> AvSalePrice { get; set; }
    }
}
