//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        public byte CompanyId { get; set; }
        public Nullable<int> TotalOwned { get; set; }
        public Nullable<decimal> PrecioPromedioCompra { get; set; }
        public Nullable<decimal> Dinero { get; set; }
        public Nullable<int> SoloCompradas { get; set; }
        public Nullable<int> SoloVendidas { get; set; }
        public Nullable<decimal> UtilidadBancaria { get; set; }
        public Nullable<decimal> UtilidadAccion { get; set; }
        public Nullable<decimal> ComisionCompra { get; set; }
        public Nullable<decimal> ComisionVenta { get; set; }
    }
}
