//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthNames
    {
        public byte id { get; set; }
        public Nullable<byte> LanguageId { get; set; }
        public Nullable<byte> MonthNumber { get; set; }
        public string MonthName { get; set; }
    }
}
