//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int id { get; set; }
        public Nullable<short> Year { get; set; }
        public string Month { get; set; }
        public Nullable<byte> MonthNumber { get; set; }
        public Nullable<decimal> MonthlySavings { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public Nullable<bool> CreatedInApp { get; set; }
    }
}
