//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedItems
    {
        public int id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<decimal> PurchaseQuantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string MPurchased { get; set; }
        public Nullable<byte> MonthNumber { get; set; }
        public Nullable<short> YPurchased { get; set; }
    }
}
