//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfLoans
    {
        public byte LoanId { get; set; }
        public string LoanDescription { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<byte> NumberOfInstallments { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AlreadyPayed { get; set; }
        public Nullable<decimal> YourCurrentDebt { get; set; }
        public Nullable<decimal> EachInstallment { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    }
}
