//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldItems
    {
        public int id { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<decimal> SaleQuantity { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string dia { get; set; }
        public Nullable<byte> DiaNumber { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string MSold { get; set; }
        public Nullable<byte> MonthNumber { get; set; }
        public Nullable<short> YSold { get; set; }
    }
}
