//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spences
    {
        public long id { get; set; }
        public Nullable<byte> SpenceId { get; set; }
        public Nullable<decimal> Spence { get; set; }
        public Nullable<System.DateTime> DSpences { get; set; }
        public string dia { get; set; }
        public Nullable<byte> DiaNumber { get; set; }
        public Nullable<byte> DiaSpences { get; set; }
        public string MSpences { get; set; }
        public Nullable<byte> MonthNumber { get; set; }
        public Nullable<short> YSpences { get; set; }
        public Nullable<bool> CreatedInApp { get; set; }
        public Nullable<bool> BankDebit { get; set; }
        public Nullable<bool> SelfLoans_AfterSync { get; set; }
        public Nullable<System.DateTime> FechaSync { get; set; }
        public string DebitUniqueIdentifier { get; set; }
    }
}
